openapi: 3.0.0
info:
  version: 1.0.0
  title: Invasive Species Catalogue API
  description: "This is an API that supports querying of invasive species information"
servers:
  - url: /api/v1
paths:
  /users:
    post:
      summary: Registers a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
              example:
                gid: "114813707989629066898"
                username: fw_user
                email: example@freshworks.io
                access_token: AbCdEf123456
      responses:
        '201':
          description: Successful registration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
              example:
                gid: "114813707989629066898"
                username: fw_user
                email: example@freshworks.io
                access_token: AbCdEf123456
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Errors"
              example:
                errors:
                  - An unexpected error occurred
  /categories:
    get:
      summary: Returns categories for invasive species
      responses:
        '200':
          description: An array of species categories
          content:
            application/json:    
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                    name:
                      type: string
                    icon:
                      type: string
                      format: byte # base64-encoded file contents
              example:
                - id: 1
                  name: Mammal
                  icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFoAAABaCAYAAAA4qEECAAARfUlEQVR4nO2da4hd13XHf2sYBmGMEMYEY+64JhpSN5h+MEEUWkwhjutPpeRDqB0a2g/GFY4bUuM4brg20cW0wSW16YvYKU0fSksoxlULFY0pwaShGGNMMSJxr4RbXYoRQhhRhBiG+ffDfq29zzl3Hpq5GrezYHTvPWc/1v7vtf9r7cc5MiEOZf9l6WYr8P9FDoFekBwCvSA5BHpBcgj0guQQ6AXJIdALkkOgFyTL+1n4ZG12BLGCaQUMYB24Np6ONvaz3m3otQzcAqyECZutG6yPp6Pr+1Wn7dXMcLI2WwLuBH0K7F7gp4DbgSOEDl0iAH0F+IngTYM3xtPRtT1RYEv9Lt4K/ALYCeBnEMcwVoBNYAO4DroM9p+IdzHeAv57PB1t7kX9NwT0ZG12FHQf2GeAXwY+ASwLsERL8UcWCcw2hUD2oRn/DJwG3hpPRx/sWpl+/e4ATkh62LAHQcdkSbeoVGq+ZWU3JUEA/z0zzgDfF/b2s9PR1d3qsmugJ2uzB4BHgftBd1SKV8CG35IwKzfKbwF2FXgT6Y/Bzo7P39gQnqzNjgAPAY8jnRAcreqO/4Yr9fWEd+yQdPED4A3glfF09PpudNox0JPjF+/D7CngVyQdAQqAXlOvPQaWEQfX6PA7ZpVtYPxAMDZ4ezwdre9It7XZCnAf6Hmw+yUth740hDCsi2SFbtBVpqBuaFzRWVyX8arBC+Pp6J2d6LZtoCMHPwC8ANwLLLXG2ysJX1K7YoOd6VffZMh4H/hTg29u13FO1mbLSL8ts5NId3sL7lMJp3urScE16BqMgGQnm2b8O/AU6F/G09Vtcfi2gI5e+jeB5wgObo5Ey+hrqITMstK+mfUlIWPDxFnMJuPp6M0t9DsBeg7sQWA505IrtKWuVE+vnl6zbCFR93LvsgU8Xt6OMWwJ9GTt4hLYZ4FvAbdtVeCgwi15BzCxOIQHR4c4h/Fl4PU2Aoi6PYj0B5jd4zOFVoWRY85KK51alQZ0GHA7ECKoR4HXtopOtpywSDwEeknSbRX3djoouhh1Oy41NxUYLlrkTIHkqCN9ppHBJ4X+BvjqZG12Sypzcnx2C9jvCJ3G7B7kVYplK3JtAtmpZird4fXMl1R0zXyN1xWA25BekvRgp9EtBvMserI2OwZ8H+lTyRwKxzai0po6RW0PxbKa6wxadBq61zF7HniRYCC/BfqaZEeSjyt+LVQyxxKTD+4dTYlmhpil8vmh4rcwPjOejj7sawLMATp68OeArzJk+XM5Tk4R6w3xfDnCMOvGVU2edeC78fsjwMpQw1xcGT4jz5YuIXm8cq/DLU1b8y1rAidtGPZ7GJOhSGmQOiTuAT43L00nTKs6zeJ9ywpba165wSlJAdkxTMkgVoAvxL+VTFNyVOPrp88QEvBJKQ+6a4OpyVLaUkZF8gS2jPE5wPmJWgZBNONh4ONdJQeoJo/DnjRylJcB8SbjrbjJGtOqpFkCLQUMXQ+2JAxIlp1u1tGs4Wb3O4GZEkddHfVDZTiBnhR4YQ3p4X5wBqgj0sZ/AHfVEUP7WX+tL0Q62CqEqqghAioCjVQcXmZyHY6sao8O0KyTYMi/JATmBXqhwzuU4We3AO8DP91HH0MWfb/QnaVyi8Mk9X4svGqHs+Q8+vxv787J+YtjBGTR6LoImpI2akCuR5AlWqiYJEUPLgpWHPpRN0v0U2VRpbHXVXFE+ShLYgTcT48MAf1pw6p7yepS2FSRFQkEz8kNDyoNxTI0ldHwTomYJjUodagf/7i6/XCn5DGc9Vq+5nU3s5LO0YZIaV2bcXndIA1g5/qXJH26D9AO0GFFjnsDFzrl/Y+hmCd9qk6rMK2OXFoVlDlT2Sml9llpiHOOob3KBtfnMVq2LrRDiTS8q/AZccB6dnT8nnVtbMCMJTPujRhW0gFa0seAO/v5sZO6aZ2C9TaJzRKNqLkerpmzPUn1BIEAtrmezP1ltZb5M02VVcrvGIfFNllfV9Vt8zm9rqH+lhLtDnqWKTpAm9kxqGeBljnam1CPJ6q8dgNsRKbG2w9XCLMuCy5ayTGGDOV7qT/xo9yQLmbYAKg0KlrXl/I1EQs4XVV076RM+mfeu52epYoejtatYMfaAWhNTDzPR9cKtA1rLL7EosXqZNGKyUO99GHpnOw3GvrOF3OmaOVVutYIWu1TvpjATb2tpzMz/WNHA4a19FAHR4AjlXWUu4M/iwd3N2SdLB16z7+j18/YJI8vB4zLLOsWki2cakAp6VdVaE411eXFtlin4xxNeHLO7sUA3QJ2pGllL3UsIy2rAURNQxMAngWUwHLOJFldGbZDI8Gi4bScGZD3gVaglUgpPr2lKbtcB0VerXBU9AUOfH+/aa9UrlS6Vtik5LZMz6Z3X3i3hNlS7SPkrMMNdUonB6echqsc6E6H1uLTHddgi1PhDKx3aCncirRS1rGK+aZwy1Kn5fg4RRsuXdW+Wic/iTLfYjfS8thIkxb1GUoCtSvrwLofvr7ixF25wLLnUytaWUmihAFrbvfzzNXnHazvfc/ZFf2kdFY6PvdKX9mujNSkDr35dDUORel0266DOnuefUBfBT5MFZSFG18iZQdjkAocZ0euriYo4DhVmVNzDJJmon7hKFtlqSK3MP1Zq1GwvZ7AwiVJHdS0s2mfkoFlyy0UWUam/kewLaCvAJf9UKy8by5ZwxhDmC25Neyw+tmgUFlHalkEOCcxR+3eMTrdKq5OHVIcsqE8CyxpmmFuDWi+uXkDoETRvhmqvtslg8stHn1Af0BYHGk9nbvgerNqoKuusf5sqUNmZYlwa/Bz/F51BiC//lK4PV/Pu9fqVpkpwrpFV81paDE7JJWOcWFfXEqfCeucT+kAHXcJ3pHYrDSsrNf96KySxe+D03Tv/FIZPUBaHPSZY13daY0iWneuqdUlx/6N/XmH3Vpw3Fqrj0f4ur2uvlQBtok4Z6Jz0GZoUekfzGyjclJud6L1rMF+Kx/eVcTzcWft2K+CmYsWKJ1TUVfJ17nmJib1zLF12tVkui4zdlDR1bfKcnhYOo0U0Wxg+vvx+e5G7RDQbwPTWn+nYLOzYlHt5LA66qusNxSMHTXIlZ9GPQ7bhFNFU/6vU6HTuez/VQ46111dqErx9iDVupYyw/UQ0NgM0Xs0ohfoeE7hzwnnz+aKer+ntYqm14P65X5aODe3OpdHvTXW5Mvx0Yd1wCr9oYKt9+Mxcw4ds64pv1cmE3pHVx8mymwD+LPx+dWd7RkCZ0HTztXGMjyGtdUnK6/5UREwN7cJ6b3p9NBBh26qjmjSlh+klbywUOjRrqOMHBG5ODvpmh1eHrEdrwlwQXCmq1CQOUDrx2CvIvU4RR8qtTzu+LzQet0gUqOTc6EA6UK20g6VDugNWvq41l0WdQe0ZTR0Vi77EeRGlJ9EhXN9mya+B7zXrwhbnusYAf8K3DWYqJJ+jzw3R6KPKms3iuns982pKpTJnAT1rc5J17aulCYZWJsfLhj8/Lxjx3NPKo2noxnwu8AWh8WjBVardercbjRvAw8qovbhHMm6HL349PWHm7Y7r+Ejjybaa/XsC96qfLHoOIKvWThdOvds99bPsEjfI3DPpq80L/vEIZeOA8itfWRPbyV9lhQLp+jDObs+mq5a6mZxnZlwUarykeb+rab1Ro4gOiuSLnfraSL9bwKvKWA0V7Z7mvQTkv7JzD6equoi0R3uidfKRK3Znu/E1K2ptWm8VUc6qXyFXM5Gl57vpdbSY8lQrElXl5fru4Dsl8bnR92goZFtPZU1no7eM7NnhC6XSpK0HtgBUu2AdM5AVACqD+SUpooYYv3mKKIvmmjLcWUUKJ1ztuIH2k7KHaFK18vAeDsgw04ef5POGPYSfgkwe+r2r7E+QBUYlBW7mK4aHxW9K0cmGuKUZoO1OmKZg96SNcNYcXvfuUD324WYFjB4AezVrjL9sqNHK04dv3jEzF4BHhEqmwONpc6NPZS8um9LDUxeDxpaR6nSWkHMSie2K4U+suiedx06IVt0DRGiQZjE/SVwciePfuzogc5nz69eRxqD/tGwTcKMKKtatogafd1sKy0UKVuIB45OD6VygzSWaqVj/dp5vSRKvlavrbt7A2ZRdI35YQP0t6DxTp+v2dVTWZO1i3eBfQt4qFhg2T7yRpojMaiGZr1ekwdv5vMWqXL6KBUenZS6oLpcJIea18N7O7M9tzIEPGcMHh1PR5eGahySXT2iPJ6u/pfgCdDfmdlGZ5ssL7iU7aSW/1KnxAaQpuVljZlyL+WhLORkJ+XKaUUUy29PH3USdnyMuy02CCA/uRuQYZcWnWRyfHa70Etm9quIpToU8rzphr7KMdreECxabrF4F7bVVJzz5JlgeCiG0FGK1l46rvYgiZldGJnymdfFNoHXgMdv5IHTG35EOU7TJ8AjklbS7nLtasqwlSPweQ4p7y/mSHHre0NTZ0gcOxSd+CipurYOehV4ZjxdfX8HsHRkT54FP7U2O2rh+cNfB1Y8/5bnQYYeq2AwOtgy8Q1ImrX21yXANoC/JtDFlRutb09eIxGekdYY+DZwPdmOn+oazqJq4iVdLMNW2WrzNJ4Ubcv9jv+6dZP6vHK67itMFk4ODdPutjsAdB34DuiZvQAZ9vB9HePp6iXQU4I/wrieogN/tsJUhjjENpW+cEPZcsf4VTjL8Z+LPeShz1fxP0M9Nc+TUmVHGes0WwdelvjyeLq6Zy8B2LPXSCQ5dXx2zIynkb6IWeewX/Y9nk/l1h0amgkhXP6nKmSISDLjtjTUUHEPTV0DXgYme2XJSfYcaMjPwHwFeFrSrf54VYkuqFDK8ThbTCCqezfK2VX+a6Bvgj2/Hy9I2ZdX/Yyno3XEi8A3zOzDep05DPS6gwtFVMumlN1mOZ4vJ/N8BzpuxtfRY0iJlwvIV0G/L+yF/XoLzb5YdJLJ8dkSpi+CfR04Vu4o+6j2CdWhqKPMOAfu+XWO2Glp8mPVIKrrJoA8AV4cT1f37RVE+/ryqvH50aZkLwNfJy+xJnJwp4uycyyhYK8ltiDnGLmbtBhQGRXZhZYOvoI0AfuT/QQZ9tmik8S3EHyBEGvH5zvkVuh64u00Q2zIpAoocnhGFZ1kcVPJ1kEKXTHsGeDbe/XepHmykNexhZeH6LvA06AYMsUwTS1fx3WOgnW+bu3p+GCabo+wuhP+UnSRVhZDj1wy8TXgO4sAGRZk0V4ma7PPCv4Q6U6/6pe3vfwQT1IFB1sFdfNEEA4gfmk8HW25z7eXchNeMKgzBk8aNvOOKm97RUv3a9g1fnV4V86S+N99xiOEzYAnBdveGdkrWbhFJzm1NnvA4BXg7tYaO1EElPvVlN06z5p3Jyn5/vuEXZGz+9KgLeSmvTLT4AeSnqA5TEkDVH4srkPD7vE4f7UNQcLvC0hfAnb1KrW9kJtm0UlOrc1OGPyFxD1mKpydpDvz3qm8B/qN8XT1R3ug7q7l5r8EVrwFnDTjXN7Kavk5bfX7766A8rWNYDiHOAn2b/vcii3lplt0ksnx2ScxTgM/K2kprKoRVkHxsfX8mWGUTdC7iM+Pz6++u5gWzJebb9FJjB8jPQa8bWblYcv0vEiZlVCva3hezmuu7wCPYZxbiO7bkANj0UlOrV2827DTwM8BS/WBrM6SX2vhm8CbwOfH09GFBam8LTk4Fh3l2bA3dxL4YdqZyfZaUbNqzMPHj0CPHTSQ4QBadJJTxy9+zLDTGL+Ifw0mXU4W2jDsDaSHx+dXd3UcYL/lwFl0kmfPr17C9Dgx9q1i6zZ2xl4HnTyoIMMBtugkk7XZUUl/ZWYPkV4VX1hjHeMs2K+Nb+Al2ouQA2vRScbT0VULp6LOgHOL4fzeGcQTBx1k+AhYdJL4lvNvkF53Jr0B9vSNvj19UfKRARrS/4KhEQBms/38Xyb2Wj5SQH+U5cBz9P8VOQR6QXII9ILkEOgFySHQC5JDoBckh0AvSA6BXpAcAr0g+V/NnclIG5z/CwAAAABJRU5ErkJggg=="
                - id: 2
                  name: Plant
                  icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFoAAABaCAYAAAA4qEECAAAN1UlEQVR4nO2dT4jdVxXHP2cYQighlOKiixeRdlYuxEUXrsS1exGRUrIRJaYxtqgl/FLMoxTU1tB2UUoXRdCl7rtwoSWGEEoJEiq8gdKM4qKEMIQSwvCOi3vPuef+fr83mUzevLmtcxYzvz/33t+933vu+Xf/PFGUIzp4WjvsCvy/0BHQK6IjoFdE6w9KcGnj1rogx4B11SjPBVBE0n8QVNO92lulpLGHYzT2zgsJnxvLZ0klZFJQWfy5Rd9XQFStMG8PuS0iVfo5sAPc72aT+YM+IYuU4fTpreOIPoPKd0BPAScRqUaAam5MbGT13oBXJL9TFDEUrIGa34+ArZTGDsiBThWR3Nn5qiATet77LTOIpa7KjLcjYKdn3Ae5DfxLVd+/uHlqNl7J/L0xoKcbW8eAHwHngaf6bBWBW4yAswiR2/dGhZ1T43bPV+qjBQwKgOXb6T1VP4cer74NNoJF6vrb9/L/+4peFeRCN5t8sKiOi2T0k8DLwFPpVtJYpHCfJnbzZ0rqcdXcGAq/EDozih+/9EdaN9pGjKrn87I1ZFQDScp9Liqli+8lg5tFTFVmqXtVXqweIJrFY/ruMZRvq+pPpk/fOskCWiSj14D1WgZqERVp6KTxoKE6eXyIVajkZjFT2hAfclXmJwT1/EUWQw1E4b6SKzNF7hTV+jumT2Ixxr32sdjeim1CdZMO0vVdGjnO0Qp3gL8hzH2Y2ZAUAZHMveKVVSU3K78n3dfg5VaFjigcVDhftQxVMXQDp6kWwVWDWDdUiPmi8i55E78E4E1ECDZuc++Wb4r06673EPk78PkYnrAA6IuzyR1VfRP0Uxu/Ntykxzmar+3j1gKx+hl4EXCXDFlZVuLAGmLsEloXILN7ydo46r3KOuqP/vBOQj3s+z5yXFwO61eVm4T++8Cfu9lkhwW00I4W4QOQKcjOuGmmNbjVdwPXYMrDGpk515WcdUHgtmglRE6OQ6GuaxkvZumMAJqu82iE3mhK4rGWI1QM49UzVZIyfQK81M0m/+kjFGkh0N3s1D3gPeC8Cp9VX+8LtshAfRCQIrPFRoS4IK+Kyso0C0bXDbGssW/iHYmjPmqpWAc4gKYFrBhT+MOsqoOGzUW4puj3utnk5jBHTbt6htkQf09gSpLbJABMpftHF1TO3heLJcCLSXVDuxYl4mLB8hbrI5or6v8itlV9NGiMSsT1KixqNjJusrjms3Y73QDOCfLhsOVDWuiwRJpubD1GsqtfAR5Lda+dDLMTit1rJRdL1VKmdmTetk4SCrdb+ZUISKPAtUT+E2V8FOuJcU1oFbEQ5bD6jQnhIso0d7SaGWUKE50j8jFwGri+F68Q9gg0wHTj1nHgxyAXgK/40CZoaq3BjbZQrLhElhr1lYMLogXMmL/npRELiUrV3hsDRD1h+WpnatghpVwF4aog57rZ5NqegMu056BSktnyLugUmNtwTQ0S7y6zQEzOBm2S3/dU94go7ZtS9f8oNnoMmcVLAlFHwaoyOLcXBWdKUkQDk3jbPhHkDOj1BTAtpD1ztNF049Y6yPPABeAJCNyFDdfAzEBQgYWq4E3R7HWq3r0qKsbpPZkcUkY3ezfSUMgD0s6B6wpnLs4mDw0y7CNM2s1O7QDvgL6iynaymTN3VXoqa/8oxCuKZlTNYQO7VYPjUNl7UamGRy7v68/WY6FEFaWfEIrLn24/UjgrqntSfGP00BxtlBXkT4FfA8e9Vi4X+wLO3mUQTO6auTDg8J6G82KGAa0ot2FofVT2bx5q8dnodUo6V/gYOH3xIWVyn/Yd+O9mk8+BN4AO9HYcuzXIaujmBobhatdmfmD5yYX1xQiB87RKr+E65nFLjWLi1WVlzlV1uRziN1dRfe5RQYZHnGHpZpN7wDsgr6qw43auWoW1BlHoGf723Bpb3pRo3VBxxfsoXiqXX/O3cn8JUgJOZhJKMUUl1DFbKzNUz4rszU5+EO1bdES6tLG1LuiLIL9UeDxycDSUY2xBVLLZWuzlvriJStVMPaJcDWLKmLP6xm6KNb5Rs2AEYJ6sCjnT7VPxjdFS5gwvziY7IG8BrwLbydUWj74lky8M0WwSSAC3tmMTSfVfQ3n4KKgUmo17zNJRf6YDkIvGtWhd6h79EOQssBRO9rYsc13HdGPrBPA8adLgWHw35hTEq/FZm8Vc2KfC9T70fTQNRkocESXfHNGbgpxeJicbLXUWvJtN7qK8DvoycNtfhMYWzyyRc6tzoGfyvOmuZ5z1bMBiv6eYhE8aV52bYxmQRoRqGC1cEeS5gwAZDmC5Qbc5uYfK24q+prATxjWjVm0vdFoHLkwzZXtc8/OKS4NJCDl9Fkc2pRXKK16sRHHyMXC2m02WKi4iHci6jm5zckeQ3wFTkG3yjEnSjQEwCBwX5vKczDC2S3c1SpJgUrpSs9xSK0dC7hwDmaNcRXm2m00+WkLTF9KBLaDpZpP7ApeB3yJ61xTkuNjNAEqwVgCoA/jF4elnj4qxhHHdUvFPmk3nGa8BZ7vNUwciLiId6EqlbjbZBt5Q5HWUneg4OAVxUL8yGVqC9TmlJ/IYdXiqJh56M+M2p5i7YS7CTZCz3ebByOQ+LdXqWETTja3jwIsKLwg8vrstkSZahxMkA6sakMHT8lyDvW1vFEHmCh8InDtocRFpJWvvkgepbwn8XtEdd+AG0zLZsRlTmv3glAfi80O3QtIfs98J4iSXcFN0tSDDijja6NLG1nGBjmRrn7Dn/WVXUQnGxTr9AP544B4vx2zlTHPgGnDmIK2LRbRSoAGmG1snQV8A+TmqJ2oZkQVAFWzuCRoNrs3AGglWjQ2b0rwriByoCbcbrRxogEtP3zopIi8Bv0BZs5gFDM009WdgbjjUfeELG3vlBLoJ+mw3O3UoIMMhAQ1JQarqBRF5HjiZcCxxir62LEGjrOxCzMTVnxaAc3lzSSuuznWzUzdW1LRROjSgAaYbW08oel6QXxHXAVYR/HFrY1ykDDj5BvBsN5scKshwyCv+u9nktiCvApdBy7q1avHF0NWun5sJXnmVc+AKcLoFkKGBrRXdbPI5qq+AXFb0LjCMf0AwRPpmXu6X4G6DXuGQrItFdKiiI9J0Y+tx0rTYz4C1YjdrECFQ++gSxIybfjdRfthtrtZOfhAdOkcbdbPJHeCCwm9AtqPJ5rNjHpwSd9eTZy2oMheRv6ry/dZAhoaAhuRBCvKaom+D7AA+o+L/RarVCVLCpjdQPX9xc/LPQ2vALtSM6IiUZ2r+DeStCv1IRqawoIak+N5bZT0fhpriaKNuNrkLOifbxhoVYojwucpM93dXX9O90wP3GR4WWXipv8AmcnOZ2KXBcVlTkxwNYZbEH8TlukRbzrzAFdVsf9QsR3u4M0zqltiyRqsup1kc4W6BmgW6uNMxYBRESG+/SX/nQ2vUrujozXIb2GVioHFke9Qs0FBCnhruywLI5sVyRc2KDiiWsy2+7/OwLLhukRrmaDXXOlNYWl4Z1viakZapYY6O53/EJTMlhKrBjm6dGuboMK2ljiwD10TjZvp2qWmgjXzZi01jZVDFlWNK1TI1DXR9nENYfRS8Q9+/eMTR+yQNi2AyxYU1tlW5PhukXWoW6Hj8Rv9UA1ujlMS32SJtQ90s0Cn8mZScVAsWcwxaLLpnb45Exz6p7JCtZ2gtqKTVfevCo2E7Guw0g8FjWzijRYwcmXePQNUCUSAIbfpvWqeGgVafp5LB5k6K16hfDBe8YaClrJ/xEwjCAkhfNRrW6zVMDcvoeJiV+lSW9Kew/FnbPN0sR9c7ryx4VJ8aZiZeNVPeKDULdCUIehvv/VHeYGQLa1qmhkUHuH0cV/+XNXa4m6Lt29HNcjTBkihTWlIpPdv+5uc4NUztcrRE9zrLaGNwT/IFWDmTqWmO9qmqXnDJZla+ABLDqV2gbVGMBixlxLoYnH7QJrULNBQQwy4tAfcUy+QszYuQdoF2JyXsB7dpLCm7spITQ/MipGllGHfExqM5o4fYuutt1C5HB+GslFNwbbFjPHVXW3cLaRnooAR97jA7KuUon/KsddnRLtCViVy2VdQXlq4c29kqHcgelrSxnieBYyOnDCSqtrXl6akgcVX1H4icMM+v/i0V8azh7LwXgPf3PL3lrz2Ocgf4727n9D8KLR3o6catr4F0oN8AOT6eajcQMnrC11HWipggdI7dKr4zCz4Ftr0I+kvFdgV+Dnym6F8E3s3H7i+Vlmp15N1UbwLfBVkrB3gTgkEp7eB3tdyMK6cUiFC2uoFzvKX1JWOpzK/6B8QmZ4aniY0yvE8gyLdInfWHZeICy5fR3wSeSeWWBYplFqQndbUAYieJ+VCOpxRQHiVcC2hx1qXP7dVZe3EvRkVFtkk6Vv+5R2j/Qlo20Mcg/XCZIjUo0VwzDsfiySX6VptuPTGRE6QwtJqb6JxtZmCU54Xi76kUs7A88y9VJ1Aui5YN9HXgRpkfCS7yYMZECsfbYyQvjilHt3kHVMt3i9rUUKR4p9XiQkRQ0aos66DesuB7qvLH5cFRaNlHZm4DF0i/tHPXf68qcK+LVLs2sD0EqoV7sSW5iapjreIpNUpKNyJufCDYPnItpeUvmGT7FLgs8KflIVLoIFzw6wo/AE4Kumbqq5ywm1OFxTF+4kw2FQpDSqUMU1qqmfHC9UXUxA1bMfLnoyCOFCtRuI/qZ93m8i2OXKe2Df0vC7XrGX7J6AjoFdER0Cui/wHGDLnjzPt5HgAAAABJRU5ErkJggg=="
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
              example:
                errors:
                  - An unexpected error occurred
  /species:
    get:
      summary: Returns a queryable list of invasive species
      parameters:
        - name: category
          in: query
          schema:
            type: string
          description: Category name to match on
          required: false
      responses:
        '200':
          description: An array of species
          content:
            application/json:    
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                    name:
                      type: string
                    latin:
                      type: string
                    introduction:
                      type: string
                      format: date
                    category:
                      type: string
              example:
                - id: 123
                  name: Norway rat
                  latin: Rattus norvegicus
                  introduction: "1880-01-01"
                  category: Mammal
                - id: 456
                  name: Giant hogweed
                  latin: Heracleum mantegazzianum
                  introduction: "1920-01-01"
                  category: Plant
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Errors"
              example:
                errors:
                  - An unexpected error occurred
    post:
      summary: Create a new species
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Species"
            example:
              name: Norway rat
              latin: Rattus norvegicus
              introduction: "1880-01-01"
              description: Brown or dark grey in colour.
              category: Mammal
      responses:
        '201':
          description: Created
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Species"
              example:
                id: 123
                name: Norway rat
                latin: Rattus norvegicus
                introduction: "1880-01-01"
                description: Brown or dark grey in colour.
                category: Mammal
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Errors"
              example:
                errors:
                  - An unexpected error occurred
  /species/${speciesId}:
    get:
      summary: Get a species by ID
      parameters:
        - in: path
          name: speciesId
          schema:
            type: integer
          required: true
          description: Numeric ID of the species to get
      responses:
        '200':
          description: An invasive species
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Species"
              example:
                id: 123
                name: Norway rat
                latin: Rattus norvegicus
                introduction: "1880-01-01"
                description: Brown or dark grey in colour.
                category: Mammal
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Errors"
              example:
                errors:
                  - An unexpected error occurred
    put:
      summary: Update a species
      parameters:
        - in: path
          name: speciesId
          schema:
            type: integer
          required: true
          description: Numeric ID of the species to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                latin:
                  type: string
                introduction:
                  type: string
                  format: date
                description:
                  type: string
                category:
                  type: string
              example:
                name: Norway rat
                latin: Rattus norvegicus
                introduction: "1880-01-01"
                description: Brown or dark grey in colour with a lighter undercoat.
                category: Mammal
      responses:
        '200':
          description: The updated species
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Species"
              example:
                id: 123
                name: Norway rat
                latin: Rattus norvegicus
                introduction: "1880-01-01"
                description: Brown or dark grey in colour with a lighter undercoat.
                category: Mammal
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Errors"
              example:
                errors:
                  - An unexpected error occurred
    delete:
      summary: Delete a species
      parameters:
        - in: path
          name: speciesId
          schema:
            type: integer
          required: true
          description: Numeric ID of the species to delete
      responses:
        '204':
          description: Species was deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Status"
              example:
                  status: Successfully deleted species.
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Errors"
              example:
                errors:
                  - An unexpected error occurred
components:
  schemas:
    User:
      properties:
        gid:
          type: string
        username:
          type: string
        email:
          type: string
          format: email
        access_token:
          type: string
          format: byte
    Species:
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        latin:
          type: string
        introduction:
          type: string
          format: date
        description:
          type: string
        category:
          type: string
    Status:
      properties:
        status:
          type: string
    Errors:
      properties:
        errors:
          type: array
          items:
            type: string